/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as OpenHousesIndexRouteImport } from './routes/open-houses/index'
import { Route as ProgramCompareIndexRouteImport } from './routes/program-compare/index'
import { Route as QuizIndexRouteImport } from './routes/quiz/index'
import { Route as SchoolsIndexRouteImport } from './routes/schools/index'
import { Route as ProgramsProgramIdIndexRouteImport } from './routes/programs/$programId/index'
import { Route as SchoolsSchoolIdIndexRouteImport } from './routes/schools/$schoolId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenHousesIndexRoute = OpenHousesIndexRouteImport.update({
  id: '/open-houses/',
  path: '/open-houses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramCompareIndexRoute = ProgramCompareIndexRouteImport.update({
  id: '/program-compare/',
  path: '/program-compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsIndexRoute = SchoolsIndexRouteImport.update({
  id: '/schools/',
  path: '/schools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdIndexRoute = ProgramsProgramIdIndexRouteImport.update({
  id: '/programs/$programId/',
  path: '/programs/$programId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsSchoolIdIndexRoute = SchoolsSchoolIdIndexRouteImport.update({
  id: '/schools/$schoolId/',
  path: '/schools/$schoolId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/students': typeof AdminStudentsRoute
  '/api/$': typeof ApiSplatRoute
  '/about/': typeof AboutIndexRoute
  '/open-houses/': typeof OpenHousesIndexRoute
  '/program-compare/': typeof ProgramCompareIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/schools/': typeof SchoolsIndexRoute
  '/programs/$programId/': typeof ProgramsProgramIdIndexRoute
  '/schools/$schoolId/': typeof SchoolsSchoolIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/students': typeof AdminStudentsRoute
  '/api/$': typeof ApiSplatRoute
  '/about': typeof AboutIndexRoute
  '/open-houses': typeof OpenHousesIndexRoute
  '/program-compare': typeof ProgramCompareIndexRoute
  '/quiz': typeof QuizIndexRoute
  '/schools': typeof SchoolsIndexRoute
  '/programs/$programId': typeof ProgramsProgramIdIndexRoute
  '/schools/$schoolId': typeof SchoolsSchoolIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/students': typeof AdminStudentsRoute
  '/api/$': typeof ApiSplatRoute
  '/about/': typeof AboutIndexRoute
  '/open-houses/': typeof OpenHousesIndexRoute
  '/program-compare/': typeof ProgramCompareIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/schools/': typeof SchoolsIndexRoute
  '/programs/$programId/': typeof ProgramsProgramIdIndexRoute
  '/schools/$schoolId/': typeof SchoolsSchoolIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/dashboard'
    | '/admin/students'
    | '/api/$'
    | '/about/'
    | '/open-houses/'
    | '/program-compare/'
    | '/quiz/'
    | '/schools/'
    | '/programs/$programId/'
    | '/schools/$schoolId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/dashboard'
    | '/admin/students'
    | '/api/$'
    | '/about'
    | '/open-houses'
    | '/program-compare'
    | '/quiz'
    | '/schools'
    | '/programs/$programId'
    | '/schools/$schoolId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/dashboard'
    | '/admin/students'
    | '/api/$'
    | '/about/'
    | '/open-houses/'
    | '/program-compare/'
    | '/quiz/'
    | '/schools/'
    | '/programs/$programId/'
    | '/schools/$schoolId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  AboutIndexRoute: typeof AboutIndexRoute
  OpenHousesIndexRoute: typeof OpenHousesIndexRoute
  ProgramCompareIndexRoute: typeof ProgramCompareIndexRoute
  QuizIndexRoute: typeof QuizIndexRoute
  SchoolsIndexRoute: typeof SchoolsIndexRoute
  ProgramsProgramIdIndexRoute: typeof ProgramsProgramIdIndexRoute
  SchoolsSchoolIdIndexRoute: typeof SchoolsSchoolIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-houses/': {
      id: '/open-houses/'
      path: '/open-houses'
      fullPath: '/open-houses/'
      preLoaderRoute: typeof OpenHousesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-compare/': {
      id: '/program-compare/'
      path: '/program-compare'
      fullPath: '/program-compare/'
      preLoaderRoute: typeof ProgramCompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools/': {
      id: '/schools/'
      path: '/schools'
      fullPath: '/schools/'
      preLoaderRoute: typeof SchoolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId/': {
      id: '/programs/$programId/'
      path: '/programs/$programId'
      fullPath: '/programs/$programId/'
      preLoaderRoute: typeof ProgramsProgramIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools/$schoolId/': {
      id: '/schools/$schoolId/'
      path: '/schools/$schoolId'
      fullPath: '/schools/$schoolId/'
      preLoaderRoute: typeof SchoolsSchoolIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminStudentsRoute: AdminStudentsRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  AboutIndexRoute: AboutIndexRoute,
  OpenHousesIndexRoute: OpenHousesIndexRoute,
  ProgramCompareIndexRoute: ProgramCompareIndexRoute,
  QuizIndexRoute: QuizIndexRoute,
  SchoolsIndexRoute: SchoolsIndexRoute,
  ProgramsProgramIdIndexRoute: ProgramsProgramIdIndexRoute,
  SchoolsSchoolIdIndexRoute: SchoolsSchoolIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
