/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchoolsIndexRouteImport } from './routes/schools/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as SchoolsSchoolIdIndexRouteImport } from './routes/schools/$schoolId/index'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsIndexRoute = SchoolsIndexRouteImport.update({
  id: '/schools/',
  path: '/schools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SchoolsSchoolIdIndexRoute = SchoolsSchoolIdIndexRouteImport.update({
  id: '/schools/$schoolId/',
  path: '/schools/$schoolId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/students': typeof AdminStudentsRoute
  '/api/$': typeof ApiSplatRoute
  '/schools/': typeof SchoolsIndexRoute
  '/schools/$schoolId/': typeof SchoolsSchoolIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/students': typeof AdminStudentsRoute
  '/api/$': typeof ApiSplatRoute
  '/schools': typeof SchoolsIndexRoute
  '/schools/$schoolId': typeof SchoolsSchoolIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/students': typeof AdminStudentsRoute
  '/api/$': typeof ApiSplatRoute
  '/schools/': typeof SchoolsIndexRoute
  '/schools/$schoolId/': typeof SchoolsSchoolIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/dashboard'
    | '/admin/students'
    | '/api/$'
    | '/schools/'
    | '/schools/$schoolId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/dashboard'
    | '/admin/students'
    | '/api/$'
    | '/schools'
    | '/schools/$schoolId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/dashboard'
    | '/admin/students'
    | '/api/$'
    | '/schools/'
    | '/schools/$schoolId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  SchoolsIndexRoute: typeof SchoolsIndexRoute
  SchoolsSchoolIdIndexRoute: typeof SchoolsSchoolIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools/': {
      id: '/schools/'
      path: '/schools'
      fullPath: '/schools/'
      preLoaderRoute: typeof SchoolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/schools/$schoolId/': {
      id: '/schools/$schoolId/'
      path: '/schools/$schoolId'
      fullPath: '/schools/$schoolId/'
      preLoaderRoute: typeof SchoolsSchoolIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminStudentsRoute: AdminStudentsRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  SchoolsIndexRoute: SchoolsIndexRoute,
  SchoolsSchoolIdIndexRoute: SchoolsSchoolIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
